clone_depth: 5

environment:
  matrix:
    - GENERATOR : "Visual Studio 15 2017 Win64"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      PLATFORM: x64

      
configuration:
  - Release

install:
  - set PATH=C:\MinGW\bin;C:\MinGW\msys\1.0;%PATH%

before_build:
  - mkdir build
  - cd build
  - cmake "-G%GENERATOR%" -DCMAKE_IGNORE_PATH="C:/Program Files/Git/usr/bin" ..

build_script:
- cmake --build .
