site_name: BehaviorTree.CPP
site_description: Introduction to Behavior Trees
site_author: Davide Faconti

copyright: 'Copyright &copy; 2018 Davide Faconti, Eurecat'

theme:
  name: 'material'
  language: en
  logo: 'images/BT.png'
  feature:
    tabs: true
  palette:
    primary: blue grey
    accent: green
  font:
    text: Ubuntu
    code: Roboto Mono
  
repo_name: 'BehaviorTree.CPP'
repo_url: 'https://github.com/BehaviorTree/BehaviorTree.CPP'

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - codehilite:
      guess_lang: true


pages:
    - Home: index.md
    
    - Learn the basics:
       - Introduction:      BT_basics.md
       - Sequence Nodes:    SequenceNode.md
       - Fallback Nodes:    FallbackNode.md
       - Decorators Nodes:  DecoratorNode.md
       
    - Tutorials: 
       - Getting started:                     getting_started.md
       - "Tutorial 1: Create a Tree":         tutorial_01_first_tree.md
       - "Tutorial 2: Basic Ports":           tutorial_02_basic_ports.md
       - "Tutorial 3: Generic ports":         tutorial_03_generic_ports.md
       - "Tutorial 4: Sequences":             tutorial_04_sequence_star.md
       - "Tutorial 5: Subtrees and Loggers":  tutorial_05_subtrees.md
       - "Tutorial 6: Ports remapping":       tutorial_06_subtree_ports.md
       - "Tutorial 7: Wrap legacy code":      tutorial_07_legacy.md
       - "Tutorial 8: Class parameters":      tutorial_08_additional_args.md
       - "Tutorial 9: Coroutines":            tutorial_09_coroutines.md
       - "The XML format":                    xml_format.md
       
    - Migration:  
        - Migrate from version 2:  MigrationGuide.md
